version: "3.7"

services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./app:/var/www/html/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"

  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm/Dockerfile
    environment:
      PHP_IDE_CONFIG: serverName=Docker server
    volumes:
      - ./app:/var/www/html/app

  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=sergey
      - MYSQL_PASSWORD=12345
      - MYSQL_DATABASE=journal
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
